### ISSUE TITLE
Define data schema for initial site launch

### ISSUE THREAD

**Issue by xtine** [hackforla/adopt-civic-art#10]
During May 2 hack night, we whiteboarded data models for initial functionality and features. As we further define the needs for the project, we should start to incorporate these columns in the app.

**Comment by BomLe** [comment]
**Artwork** 
* ID
* Title
* Description
* Lat
* Long
* Image
* Check ins
* Artist (Full Name)
* Artist First
* Artist Last
* Date
   * Date Description
* Artwork Type
* Medium
* Location Name
* Street 1
* Street 2
* City
* State
* Zip

**Comment by BomLe** [comment]
**User**
* ID
* Username
* First
* Last
* Adopted Artworks
* Email

**Comment by BomLe** [comment]
**Check In Data**
* Image (req'd)
   * Multiple uploads (capped)
* Condition (choices)
   * Good
   * Damaged
* Damaged (choices) (optional)
   * Damage 1
   * Damage 2
   * Damage 3
   * Damage 4
   * Damage 5
* Other (text field) (optional)
* User
* Timestamp

**Comment by BomLe** [comment]
**Image**
* Author
* URL
* Licensing/attribution
* Caption

**Comment by xtine** [comment]
At our June 6 hack night meeting, we further defined the details of the schema:

<img width="800" alt="screen shot 2017-06-06 at 8 38 35 pm" src="https://user-images.githubusercontent.com/24054/26861374-37ba94de-4af8-11e7-9717-c061c80534f4.png">
