### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by jojoleung** [hackforla/adopt-civic-art#38]
As user, I want to understand the value proposition quickly. As user (or repeat user), I want to access the core content quickly.

**Acceptance criteria**

- [x] Design landing page
- [ ] Create Illustrations for landing page
- [x] Create copy for landing page
- [ ] Source photography for landing page
- [ ] Implement Landing Page

**Comment by BomLe** [comment]
@xtine Having an issue with content entered through back end not displaying correctly on front end.

Copy entered on back end:
![about-back](https://user-images.githubusercontent.com/24551220/33966266-d3f4fa78-e013-11e7-98fc-1a96ecfeacdf.PNG)

Copy displayed on front end:
![aboutsection](https://user-images.githubusercontent.com/24551220/33966279-d9815edc-e013-11e7-9aad-87a6bb6e5c9c.PNG)

**Comment by xtine** [comment]
Just fixed on dev:
![screencapture-demo-adopt-civic-art-herokuapp-about-1513230562006](https://user-images.githubusercontent.com/24054/33977401-f1dfb23c-e057-11e7-95e2-a5779404eceb.png)
