### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by matikin9** [hackforla/adopt-civic-art#5]
Data sanitizing/escaping for DB storage & HTML display?

**Comment by BomLe** [comment]
Working on cleaning larger dataset from County Open Data Portal: https://data.lacounty.gov/Arts-and-Culture/Los-Angeles-County-Civic-Art-Collection/9qv9-dayy

**Comment by BomLe** [comment]
Smaller dataset (10 artworks) clean: https://docs.google.com/spreadsheets/d/1BN5343PBcE7OyGTZjRBWvBScP8Ks1mVBQp-WKwRUMYc/edit?usp=sharing
